title: NAPPLab Robotics Lab @ Colorado School of Mines
repository: TheNAPPLab/TheNAPPLab.github.io

name: NAPPLab Robotics Lab @ Colorado School of Mines
description: The Navigation, Aerial-robots, and Perception Planning Lab @ Colorado School of Mines
url: https://www.napplab.org

exclude: [bibble, README.md, Makefile, screenshot.png, vendor, venv]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  # - key: postdoc
  #   name: Postdocs
  - key: masters
    name: Master's Students
  - key: phd
    name: PhD Students
  - key: intern
    name: Undergraduate Researchers
  - key: visitor
    name: Visiting Students
  # - key: postdoc-alum
  #   name: Past Postocs
  # - key: phd-alum
  #   name: Past PhD Students
  # - key: masters-alum
  #   name: Past Master's Students
  - key: intern-alum
    name: Past Undergraduate Researchers and Interns
  # - key: visitor-alum
  #   name: Past Visiting Students and Faculty



includes_dir: website-assets/_includes
layouts_dir: website-assets/_layouts
sass:
  sass_dir: website-assets/_sass
asset_dir: /website-assets/assets

# Number of news stories on the front page.
front_page_news: 8

# Number of old projects on the front page
front_page_old_projects: 4

# Base pathname for links.
base: ""
baseurl: ""

# make pages for the _projects folder
collections:
  projects:
    output: true
  events:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications/
  # - title: Events
  #   link: /events.html
  - title: Contact
    link: /contact.html
  # - title: Blog
  #   link: /blog.html

# Includes
include: ['_pages']

plugins:
    - jekyll-paginate
    - ['jekyll/scholar']
    - jemoji


# Build settings
markdown: kramdown
highlighter: pygments

# Jekyll-Scholar
scholar:

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en"]
